apiVersion: apps/v1
kind: Deployment
metadata:
  name: plusman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plusman
  template:
    metadata:
      labels:
        app: plusman
    spec:
      containers:
      - name: server
        image: ghcr.io/skkra0/plusman:release
        imagePullPolicy: IfNotPresent
        ports: [{ containerPort: 3000 }]
        readinessProbe: { httpGet: { path: "/", port: 3000 } }
        livenessProbe: { httpGet: { path: "/_next", port: 3000 } }
        env:
          - name: POSTGRES_URL
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: POSTGRES_URL
