apiVersion: apps/v1
kind: Deployment
metadata:
  name: plusman
spec:
  replicas: 3
  selector:
    matchLabels:
      app: plusman
  template:
    metadata:
      labels:
        app: plusman
    spec:
      containers:
      - name: server
        image: ghcr.io/skkra0/plusman:release
        imagePullPolicy: IfNotPresent
        ports: [{ containerPort: 3000 }]
        readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 5
        env:
          - name: POSTGRES_URL
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: POSTGRES_URL
